export const styles = {
  root: { display: 'flex', height: '100vh', fontFamily: "'Segoe UI', sans-serif", overflow: 'hidden' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', zIndex: 40 },
  sidebar: { width: '230px', background: '#0f1623', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  logoArea: { padding: '20px 16px 16px', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', alignItems: 'center', gap: '10px' },
  logoBadge: { width: '32px', height: '32px', borderRadius: '8px', background: '#005691', color: '#fff', fontWeight: '800', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  logoText: { color: '#fff', fontWeight: '700', fontSize: '17px', letterSpacing: '0.01em' },
  nav: { flex: 1, padding: '16px 10px', display: 'flex', flexDirection: 'column', gap: '2px' },
  navGroup: { margin: '0 0 8px 8px', fontSize: '10px', fontWeight: '600', color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '0.08em' },
  navItem: { position: 'relative', display: 'flex', alignItems: 'center', gap: '10px', padding: '9px 12px', borderRadius: '10px', cursor: 'pointer', transition: 'background 0.15s' },
  navItemActive: { background: 'rgba(0, 86, 145, 0.25)' },
  navIcon: { flexShrink: 0, display: 'flex' },
  navLabel: { fontSize: '14px' },
  activeBar: { position: 'absolute', left: 0, top: '50%', transform: 'translateY(-50%)', width: '3px', height: '60%', borderRadius: '0 3px 3px 0', background: '#005691' },
  sidebarUser: { padding: '12px 14px', borderTop: '1px solid rgba(255,255,255,0.07)', display: 'flex', alignItems: 'center', gap: '10px' },
  sidebarAvatar: { width: '32px', height: '32px', borderRadius: '50%', background: '#005691', color: '#fff', fontWeight: '700', fontSize: '14px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  sidebarUserInfo: { overflow: 'hidden' },
  sidebarUserName: { margin: 0, fontSize: '13px', fontWeight: '600', color: '#fff', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  sidebarUserRole: { margin: '1px 0 0', fontSize: '11px', color: 'rgba(255,255,255,0.45)' },
  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', background: '#f4f6fb' },
  header: { background: '#fff', borderBottom: '1px solid #e5e7eb', padding: '0 24px', height: '52px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
  pageTitle: { fontSize: '15px', fontWeight: '600', color: '#111827' },
  headerRight: { display: 'flex', alignItems: 'center', gap: '12px' },
  avatar: { width: '34px', height: '34px', borderRadius: '50%', background: '#005691', color: '#fff', fontWeight: '700', fontSize: '14px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  menuBtn: { display: 'flex', alignItems: 'center', background: 'transparent', border: 'none', cursor: 'pointer', color: '#111827', padding: '4px' },
  logoutBtn: { display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 12px', background: 'transparent', border: '1px solid #e5e7eb', borderRadius: '8px', color: '#6b7280', fontSize: '13px', cursor: 'pointer' },
  content: { flex: 1, overflow: 'auto', padding: '24px 28px' },
};