export const styles = {
  wrapper: { display: 'flex', flexDirection: 'column', gap: '20px', height: '100%' },
  pageHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
  iconWrap: { width: '40px', height: '40px', borderRadius: '10px', background: '#e8f0fe', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  pageTitle: { margin: 0, fontSize: '20px', fontWeight: '700', color: '#111827', lineHeight: 1.2 },
  pageSubtitle: { margin: '2px 0 0', fontSize: '13px', color: '#6b7280' },
  statusBadge: { display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 14px', background: '#f3f4f6', color: '#6b7280', borderRadius: '999px', fontSize: '13px', fontWeight: '600', flexShrink: 0 },
  statusDot: { width: '8px', height: '8px', borderRadius: '50%', background: '#9ca3af', display: 'inline-block' },
  mapCard: { background: '#fff', borderRadius: '16px', border: '1px solid #e5e7eb', overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,0.06)', display: 'flex', flexDirection: 'column' },
  mapCardHeader: { display: 'flex', alignItems: 'center', padding: '12px 16px', borderBottom: '1px solid #f3f4f6', background: '#fafafa' },
  mapCardHeaderLeft: { display: 'flex', alignItems: 'center', gap: '6px' },
  mapCardHeaderText: { fontSize: '13px', color: '#6b7280', fontWeight: '500' },
  mapContainer: { height: 'calc(100vh - 220px)', minHeight: '300px', width: '100%', zIndex: 0 },
  adminActions: { display: 'flex', borderTop: '1px solid #f3f4f6' },
  actionBtn: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', padding: '14px', fontSize: '14px', fontWeight: '600', border: 'none', cursor: 'pointer' },
  startBtn: { background: '#16a34a', color: '#fff' },
  endBtn: { background: '#dc2626', color: '#fff' },
};