FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10 --activate

COPY client-admin/package.json ./

RUN pnpm install

COPY client-admin/ ./

EXPOSE 5173

CMD ["node_modules/.bin/vite", "--host", "0.0.0.0","--port" , "5173"]
