FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl

RUN corepack enable && corepack prepare pnpm@10 --activate

COPY package.json ./

RUN pnpm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3011

CMD ["node_modules/.bin/nodemon","index.js"]
